services:

  redis:
    image: redis/redis-stack:latest
    container_name: pre-entrega-7-redis
    ports:
      - "6376:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  phoenix:
    image: arizephoenix/phoenix:latest
    container_name: pre-entrega-7-phoenix
    ports:
      - "6006:6006"
    restart: unless-stopped

volumes:

  redis_data:
